import type { GetServerSideProps, NextPage } from "next";
import { Session } from "next-auth";
import { signOut } from "next-auth/react";

import Head from "next/head";
import Button from "../components/button/button";
import Nav from "../components/nav/nav";
import MainLayout from "../layouts/main.layout";
import { getServerSidePropsWithSession } from "../utils/auth";

type HomeProps = { sesh: Session };

export const getServerSideProps: GetServerSideProps<HomeProps> = getServerSidePropsWithSession(
  async ({ session }) => {
    return {
      props: {
        sesh: session,
      },
    };
  },
);

const Home: NextPage<HomeProps> = (props) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className="h-screen">
          <div className="flex flex-row gap-10"></div>
        </div>
        <div className="h-screen">hey</div>
      </MainLayout>
    </>
  );
};

export default Home;
